### ISSUE TITLE
Set up file store db

### ISSUE THREAD

**Issue by RaymondDashWu** [Insight-Generator/DS-ML-DL#5]

**Comment by mattluu** [comment]
Can you elaborate a bit on the name of this ticket?

My initial thoughts were that we were not going to create dynamic tables per file. Instead, we will just have an endpoint which will:
* Open the file if it exists
* Parse data and return rows with the selected columns

It definitely won't be a fast process nor will it be an efficient one as we do things this way but it's probably one that needs better design rather than dynamic tables / nosql solutions which won't scale well. What we should make sure we do though is to make sure whatever way we DO do it, we have an obvious way to another step

**Comment by mattluu** [comment]
Ticket has been recreated as bilight:#5
